css-brochure-form-Dylan De Vei
dylandevei/c0322-code-solutions pull request #15
Opened 2022-03-17 16:59 UTC by dylandevei

![Screen Shot 2022-03-17 at 9 41 16 AM](https://user-images.githubusercontent.com/99229316/158853860-6506b167-cbcd-4ab6-96d7-314f3b727539.png)

2022-03-17 17:32 UTC, codingcodymiller requested changes
Great work! A few notes for you:

2022-03-17 17:32 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +}
I don't think this is doing anything for you.

2022-03-17 17:32 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +#hiring {
You should stick to applying styling to classes rather than ids.

2022-03-17 17:32 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +#engineers {
You should stick to applying styling to classes rather than ids.

2022-03-17 19:02 UTC, dylandevei commented
![Screen Shot 2022-03-17 at 12 00 33 PM](https://user-images.githubusercontent.com/99229316/158876749-6dfce0a1-5275-4a2a-a64b-f441def8e61d.png)
updated some stuff dont think I figured everything out. Was just pushing so I could get back to main.

2022-03-17 21:39 UTC, codingcodymiller requested changes
Hey dude! Just throwing a review your way so I know when this is actually ready for another review 🤓

2022-03-22 02:45 UTC, dylandevei commented
https://user-images.githubusercontent.com/99229316/159397554-10fd9c8e-ab3c-4e54-95d9-1dddf5165ea8.mov
Here are the final changes for css-brochure-form

2022-03-23 19:54 UTC, codingcodymiller approved these changes
Nice work!!

2022-03-23 20:04 UTC, merged