css-three-column-layout-Dylan De Vei
dylandevei/c0322-code-solutions pull request #18
Opened 2022-03-18 06:00 UTC by dylandevei

![Screen Shot 2022-03-17 at 10 59 05 PM](https://user-images.githubusercontent.com/99229316/158946167-0ef3134a-ea5b-441b-87fa-76c2b8073ad0.png)

2022-03-18 18:09 UTC, codingcodymiller requested changes
Hey Dylan! your circles are too large as compared to the example, please revise and submit a new screenshot with your revision

2022-03-18 18:59 UTC, dylandevei commented
<img width="1432" alt="Screen Shot 2022-03-18 at 11 58 21 AM" src="https://user-images.githubusercontent.com/99229316/159067585-6408ec93-1d43-4fe2-99c8-7b9237a9a173.png">
Revisions for the challenge (hope they are right!)

2022-03-18 22:41 UTC, codingcodymiller requested changes

2022-03-18 22:41 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
The only styling that should be on a `column` class is `width` or `flex-basis`. Make sure the measurement accurately matches the name of the class as well 🤓 . If you need any other additional styling on top of `width` or `flex-basis`, you should make a separate class that you can add to the element in addition to the `column` class.

2022-03-18 22:41 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
The only styling that should be on a `column` class is `width` or `flex-basis`. Make sure the measurement accurately matches the name of the class as well 🤓 . If you need any other additional styling on top of `width` or `flex-basis`, you should make a separate class that you can add to the element in addition to the `column` class.

2022-03-18 22:41 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
You have an extra curly brace here 👀

2022-03-19 00:36 UTC, dylandevei commented
![Screen Shot 2022-03-18 at 5 34 31 PM](https://user-images.githubusercontent.com/99229316/159099729-779c9d36-bf65-4f49-b84f-25236b880198.png)
Revisions (progress).

2022-03-21 17:28 UTC, codingcodymiller approved these changes
Great work!!

2022-03-21 17:38 UTC, merged