Css canvas medical-Dylan De Vei
dylandevei/c0322-code-solutions pull request #21
Opened 2022-03-21 04:27 UTC by dylandevei

https://user-images.githubusercontent.com/99229316/159205481-1ed56659-d16a-4f3a-94bb-b57da54b4daf.mov

![Screen Shot 2022-03-20 at 9 26 03 PM](https://user-images.githubusercontent.com/99229316/159205399-cc32b82f-5e9d-40c9-bf2d-88bce89167cc.png)
![Screen Shot 2022-03-20 at 9 26 11 PM](https://user-images.githubusercontent.com/99229316/159205408-2fc248c9-40bb-4bf2-8f61-f06244864284.png)

2022-03-21 19:34 UTC, codingcodymiller requested changes
Great work!! A few notes for you:

2022-03-21 19:34 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-fourth"></div>
You should never have empty `column` elements. Instead, you should make the previous `column-fourth` into a `column-half`

2022-03-21 19:34 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-one-third"></div>
Same deal here, no empty `column` elements

2022-03-21 19:34 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-fourth"></div>
Same deal here, no empty `column` elements

2022-03-21 19:34 UTC, codingcodymiller commented on css-canvas-medical/index.html
> +      <div class="column-one-third"></div>
Same deal here, no empty `column` elements

2022-03-22 03:13 UTC, dylandevei commented
https://user-images.githubusercontent.com/99229316/159400505-f27da00d-95f0-4476-8368-2faa9f7fe74f.mov

revisions to canvas medical, I took out the empty column elements and adjusted some minor things.

2022-03-22 18:38 UTC, codingcodymiller approved these changes
Great work!! 🎉

2022-03-22 18:38 UTC, merged