javascript-arrays exercise.-Dylan De Vei
dylandevei/c0322-code-solutions pull request #25
Opened 2022-03-21 23:57 UTC by dylandevei

![Screen Shot 2022-03-21 at 4 55 27 PM](https://user-images.githubusercontent.com/99229316/159381735-be509ce3-6532-462c-a6d2-7d6f63f8839a.png)

2022-03-21 23:58 UTC, codingcodymiller requested changes

2022-03-21 23:58 UTC, codingcodymiller commented on javascript-arrays/main.js
> +var lastIndex = students[3];
What if the array was longer or shorter? You should determine the last index programmatically.

2022-03-22 00:02 UTC, codingcodymiller approved these changes

2022-03-22 00:02 UTC, dylandevei commented
![Screen Shot 2022-03-21 at 5 01 07 PM](https://user-images.githubusercontent.com/99229316/159382144-2050fb50-181f-48eb-8176-fbaefa544885.png)
![Screen Shot 2022-03-21 at 5 01 04 PM](https://user-images.githubusercontent.com/99229316/159382146-c4748886-689a-4754-ba69-7e4263e0830c.png)
Here are those changes

2022-03-22 00:03 UTC, merged