javascript-loops-practice exercise.-Dylan De Vei
dylandevei/c0322-code-solutions pull request #35
Opened 2022-03-25 07:07 UTC by dylandevei

https://user-images.githubusercontent.com/99229316/160071484-afa1702b-90ea-4225-8b94-826491cee68b.mov

2022-03-25 17:12 UTC, codingcodymiller requested changes
Hey Dylan! In addition to my other comments, please move all your return statements to their own line, you should never have a return statement on the same line as a closing bracket.

2022-03-25 17:12 UTC, codingcodymiller commented on javascript-loops-practice/find-index.js
> +  } if (value > array.length) {
Why `value > array.length`? Is this function checking if the `value` given is larger than the length of the array to search?

2022-03-25 17:12 UTC, codingcodymiller commented on javascript-loops-practice/includes-seven.js
> +  } if (sevenArray > 0) {
I believe you meant `sevenArray.length`

2022-03-26 06:00 UTC, dylandevei commented
![Screen Shot 2022-03-25 at 10 57 41 PM](https://user-images.githubusercontent.com/99229316/160226952-d802ef8a-5e51-4b8c-8f6b-7358c35b5b88.png)
made the necessary revisions to code and made moved return to their own lines

2022-03-28 17:35 UTC, codingcodymiller approved these changes

2022-03-28 17:51 UTC, merged