completed array-manipulation 1-exercise-Dylan De Vei
dylandevei/c0322-code-solutions pull request #37
Opened 2022-03-26 02:49 UTC by dylandevei

https://user-images.githubusercontent.com/99229316/160221961-bb85cd4f-4ebe-4abb-b473-4960382af3fc.mov

2022-03-28 19:01 UTC, codingcodymiller requested changes

2022-03-28 19:01 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +// first index will be taken off of the array
These steps sound like they correlate with `tail`, not `initial`

2022-03-28 19:01 UTC, codingcodymiller commented on array-manipulation-1/src/reverse.js
> +  } return reverseArray;
Please always keep `return` statements on their own line

2022-03-28 19:01 UTC, codingcodymiller commented on array-manipulation-1/src/tail.js
> +  } return tail;
Please always keep `return` statements on their own line

2022-03-28 19:01 UTC, codingcodymiller commented on array-manipulation-1/src/initial.js
> +  } return initial;
Please always keep `return` statements on their own line

2022-03-28 19:01 UTC, codingcodymiller commented on array-manipulation-1/src/compact.js
> +  } return newArray;
Please always keep `return` statements on their own line

2022-03-28 19:54 UTC, dylandevei commented
![Screen Shot 2022-03-28 at 12 53 08 PM](https://user-images.githubusercontent.com/99229316/160476234-bf40adaf-7090-4b89-a778-ded71d2e7863.png)


did those requests ! Thank you for the advice :)

2022-03-29 17:52 UTC, codingcodymiller approved these changes

2022-03-29 18:49 UTC, merged