javascript-light-bulb challenge.-Dylan De Vei
dylandevei/c0322-code-solutions pull request #43
Opened 2022-03-29 18:49 UTC by dylandevei

https://user-images.githubusercontent.com/99229316/160683595-e4238c43-16ca-4e39-b70f-3b4a05edf96a.mov

2022-03-29 19:33 UTC, codingcodymiller requested changes

2022-03-29 19:33 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  buttonClicks++;
Rather than using a counter variable then checking if the value is even or odd, I would suggest using a boolean to keep track of if the light is currently on or off, and re-assign the value to the opposite boolean every time the user clicks the light switch.

2022-03-29 19:33 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  }
Does this work more than once? Your lightbulb needs to be infinitely toggleable, not just once.

2022-03-29 23:32 UTC, dylandevei commented
https://user-images.githubusercontent.com/99229316/160723006-631be13a-a07c-4d80-bc34-9f87c166d3c2.mov

made the necessary changes:
-incorporate boolean values
-made lightbulb be able to switch on and off

2022-03-30 17:54 UTC, codingcodymiller approved these changes
Nice work!!

2022-03-30 18:52 UTC, merged