javascript-timers exercise.-Dylan De Vei
dylandevei/c0322-code-solutions pull request #63
Opened 2022-04-13 18:44 UTC by dylandevei

https://user-images.githubusercontent.com/99229316/163248742-54b80df1-5a96-4671-9f7f-f3ebf7e583c0.mov

2022-04-13 19:30 UTC, codingcodymiller requested changes

2022-04-13 19:30 UTC, codingcodymiller commented on javascript-timers/interval.js
> +setInterval(countdown, 1000);
Make sure you save the id so you can clear the interval later

2022-04-14 17:47 UTC, dylandevei commented
![Screen Shot 2022-04-14 at 10 46 36 AM](https://user-images.githubusercontent.com/99229316/163446592-19157734-f01e-4c61-9b78-845372b3494e.png)

went ahead and stored the setInterval in a variable so I am able to clear it later on in the file. Thank you for the tip!

2022-04-18 04:50 UTC, codingcodymiller approved these changes

2022-04-29 21:51 UTC, merged